# Numpy

Numeric Python

In [ ]:
list - collection of different type of elements

array - collection of similar type of elements

In [ ]:
    10      20     30    
   2011    2013   2015
    0        1      2

In [1]:
!pip install numpy

# 1 | Creating a Vector

In [2]:
import numpy as np

In [3]:
np.array?

In [4]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [5]:
print(v)

[1 2 3 4]


In [6]:
type(v)

numpy.ndarray

In [7]:
c = np.array([[1], [2], [3]])
c

array([[1],
       [2],
       [3]])

# 2 | Matrix

In [8]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
0th dimension -->   .
1st dimension -->   .______.

2nd dimension -->   .___|___.

3rd dimension -->   .___|___.
                       /

4th dimension

### Linear Algebra

# 3 | Selecting Elements

In [10]:
v = np.array([1,2,3,4,5,6,7])
print(v[0])

1


In [11]:
v[:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
v[3:6]

array([4, 5, 6])

In [13]:
v[-1]

7

In [15]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
matrix[0,0]  # [row, column]

1

In [17]:
matrix[1,1]

5

In [18]:
matrix[2,1]

8

In [19]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

In [21]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
matrix[:, 2:3]

array([[3],
       [6],
       [9]])

In [23]:
print(matrix[:,3:2])

[]


In [24]:
matrix[:,3:2]

array([], shape=(3, 0), dtype=int32)

In [25]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
matrix[0:3:2, 0:3:]

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
matrix[0:3:2, 0:3:2]

array([[1, 3],
       [7, 9]])

In [28]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
matrix[-3:-1:, -3:-2:]

array([[1],
       [4]])

# 4 | Describe a Matrix

In [32]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9],[1,2,3]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [33]:
matrix.shape

(4, 3)

In [34]:
matrix.size

12

In [35]:
matrix.ndim

2

# 5 | Max and min values

In [36]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(np.max(matrix))

9


In [38]:
print(np.min(matrix))

1


In [39]:
print(np.max(matrix, axis = 0))  # column

[7 8 9]


In [40]:
print(np.max(matrix, axis = 1))  # rows

[3 6 9]


In [41]:
print(np.max(matrix, axis = 0)[1])

8


# 6 | mean variance and standard deviation

In [42]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
print(np.mean(matrix))

5.0


In [44]:
print(np.std(matrix))

2.581988897471611


In [45]:
print(np.var(matrix))

6.666666666666667


# 7 | Reshaping arrays

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(matrix.reshape(9))

[1 2 3 4 5 6 7 8 9]


In [4]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [5]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [6]:
print(matrix.reshape(1,-1)) # possible number of columns

[[1 2 3 4 5 6 7 8 9]]


In [7]:
print(matrix.flatten())  # conver it in single dimension

[1 2 3 4 5 6 7 8 9]


# 8 | transpose of matrix

In [8]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 9 | Determinant and rank

In [10]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(np.linalg.det(matrix))

-9.51619735392994e-16


In [12]:
print(np.linalg.matrix_rank(matrix))

2


# 10 | Diagonal

In [13]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(matrix.diagonal())

[1 5 9]


In [15]:
print(matrix.diagonal(offset = 1))

[2 6]


In [16]:
print(matrix.diagonal(offset = -1))

[4 8]


In [17]:
print(matrix.diagonal(offset = 2))

[3]


# 11 | Trace

In [18]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
matrix.trace()

15

In [20]:
matrix.trace?

# 12 | Dot product

In [23]:
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix1)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(np.dot(matrix1, matrix2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# 13 | cross product

In [25]:
print(matrix1 * matrix2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [26]:
print(np.add(matrix1, matrix2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [27]:
print(np.subtract(matrix1, matrix2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
print(matrix1 + matrix2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# 14 | Random values

In [33]:
np.random.randint(0,11,5)

array([10, 10,  0,  3,  0])

In [35]:
np.random.randint(0,11,9)

array([ 2, 10,  2,  8,  8,  3,  0,  6,  4])

In [37]:
np.random.randint(0,11,9).reshape(3,3)

array([[2, 5, 6],
       [1, 4, 6],
       [4, 6, 6]])

In [46]:
np.random.seed(1)

np.random.randint(0,11,3)

array([5, 8, 9])

In [47]:
np.random.normal(1.0, 2.0, 10)
#               mean, std

array([-0.60434568,  0.10224438, -1.21187015, -2.3090309 , -3.72693721,
        3.2706907 , -1.03402827,  2.27472363, -0.71981321,  4.54521526])

In [48]:
np.random.normal(1.0, 2.0, 10).reshape(10,1)
#               mean, std

array([[-1.22072611],
       [ 1.36242853],
       [ 2.12868973],
       [-0.13302046],
       [ 2.45995119],
       [ 1.74598758],
       [ 2.06762182],
       [ 0.8160534 ],
       [ 4.82764078],
       [ 1.66159426]])

In [49]:
np.random.normal(1.0, 2.0, 10).reshape(2,5)
#               mean, std

array([[ 3.28388504, -1.25919032, -0.70010475,  2.92164001,  0.56516365],
       [ 1.31702977,  2.74683647,  0.77723326, -1.07607753, -1.01895965]])