# Decision Tree

<img src='dt.png' />

In [1]:
import pandas as pd

df = pd.read_csv("datasets/salaries.csv")
df.head()

company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [2]:
salary_df = df.drop('salary_more_then_100k', axis = 'columns')

salary_df

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [3]:
target = df['salary_more_then_100k']

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [6]:
# help(le)

In [7]:
salary_df['company_number'] = le.fit_transform(salary_df['company'])
salary_df['job_number'] = le.fit_transform(salary_df['job'])
salary_df['degree_number'] = le.fit_transform(salary_df['degree'])

In [8]:
salary_df

company                  job     degree  company_number  job_number  \
0       google      sales executive  bachelors               2           2   
1       google      sales executive    masters               2           2   
2       google     business manager  bachelors               2           0   
3       google     business manager    masters               2           0   
4       google  computer programmer  bachelors               2           1   
5       google  computer programmer    masters               2           1   
6   abc pharma      sales executive    masters               0           2   
7   abc pharma  computer programmer  bachelors               0           1   
8   abc pharma     business manager  bachelors               0           0   
9   abc pharma     business manager    masters               0           0   
10    facebook      sales executive  bachelors               1           2   
11    facebook      sales executive    masters               1           2   
12    facebook     business manager  bachelors               1           0   
13    facebook     business manager    masters               1           0   
14    facebook  computer programmer  bachelors               1           1   
15    facebook  computer programmer    masters               1           1   

    degree_number  
0               0  
1               1  
2               0  
3               1  
4               0  
5               1  
6               1  
7               0  
8               0  
9               1  
10              0  
11              1  
12              0  
13              1  
14              0  
15              1

In [9]:
salary_df = salary_df.drop(['company', 'job', 'degree'], axis = 'columns')

salary_df

company_number  job_number  degree_number
0                2           2              0
1                2           2              1
2                2           0              0
3                2           0              1
4                2           1              0
5                2           1              1
6                0           2              1
7                0           1              0
8                0           0              0
9                0           0              1
10               1           2              0
11               1           2              1
12               1           0              0
13               1           0              1
14               1           1              0
15               1           1              1

In [10]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [11]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(salary_df, target)

DecisionTreeClassifier()

In [12]:
model.score(salary_df, target)

1.0

In [14]:
model.predict([[2, 1, 0]])

C:\Users\himan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [15]:
model.predict([[2, 1, 1]])

C:\Users\himan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

# Preprocessing

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit([1,2,2,6])

LabelEncoder()

In [17]:
le.classes_

array([1, 2, 6])

In [19]:
le.transform([1,1,2,6])

array([0, 0, 1, 2], dtype=int64)

In [22]:
le.inverse_transform([2])

array([6])

In [23]:
le.fit(['paris', 'paris', 'goa', 'mumbai'])

LabelEncoder()

In [24]:
le.classes_

array(['goa', 'mumbai', 'paris'], dtype='<U6')

In [25]:
le.transform(['goa', 'goa', 'paris'])

array([0, 0, 2])

In [26]:
le.inverse_transform([0,2])

array(['goa', 'paris'], dtype='<U6')

# Income Prediction

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
df = pd.read_csv('datasets/adult_dataset.csv')
df.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [30]:
df1 = df[df.workclass == '?']
df1

age workclass  fnlwgt     education  education.num      marital.status  \
0       90         ?   77053       HS-grad              9             Widowed   
2       66         ?  186061  Some-college             10             Widowed   
14      51         ?  172175     Doctorate             16       Never-married   
24      61         ?  135285       HS-grad              9  Married-civ-spouse   
44      71         ?  100820       HS-grad              9  Married-civ-spouse   
...    ...       ...     ...           ...            ...                 ...   
32533   35         ?  320084     Bachelors             13  Married-civ-spouse   
32534   30         ?   33811     Bachelors             13       Never-married   
32541   71         ?  287372     Doctorate             16  Married-civ-spouse   
32543   41         ?  202822       HS-grad              9           Separated   
32544   72         ?  129912       HS-grad              9  Married-civ-spouse   

      occupation   relationship                race     sex  capital.gain  \
0              ?  Not-in-family               White  Female             0   
2              ?      Unmarried               Black  Female             0   
14             ?  Not-in-family               White    Male             0   
24             ?        Husband               White    Male             0   
44             ?        Husband               White    Male             0   
...          ...            ...                 ...     ...           ...   
32533          ?           Wife               White  Female             0   
32534          ?  Not-in-family  Asian-Pac-Islander  Female             0   
32541          ?        Husband               White    Male             0   
32543          ?  Not-in-family               Black  Female             0   
32544          ?        Husband               White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
2              4356              40  United-States  <=50K  
14             2824              40  United-States   >50K  
24             2603              32  United-States  <=50K  
44             2489              15  United-States  <=50K  
...             ...             ...            ...    ...  
32533             0              55  United-States   >50K  
32534             0              99  United-States  <=50K  
32541             0              10  United-States   >50K  
32543             0              32  United-States  <=50K  
32544             0              25  United-States  <=50K  

[1836 rows x 15 columns]

In [31]:
df = df[df.workclass != '?']
df.head()

age workclass  fnlwgt     education  education.num marital.status  \
1   82   Private  132870       HS-grad              9        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   
5   34   Private  216864       HS-grad              9       Divorced   
6   38   Private  150601          10th              6      Separated   

          occupation   relationship   race     sex  capital.gain  \
1    Exec-managerial  Not-in-family  White  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   
5      Other-service      Unmarried  White  Female             0   
6       Adm-clerical      Unmarried  White    Male             0   

   capital.loss  hours.per.week native.country income  
1          4356              18  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K  
5          3770              45  United-States  <=50K  
6          3770              40  United-States  <=50K

In [32]:
df_categorical = df.select_dtypes(include = ['object'])

df_categorical.apply(lambda x: x == '?', axis = 0 ).sum()

workclass           0
education           0
marital.status      0
occupation          7
relationship        0
race                0
sex                 0
native.country    556
income              0
dtype: int64

In [33]:
df = df[df.occupation != '?']

df = df[df['native.country'] != '?']

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 1 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             30162 non-null  int64 
 1   workclass       30162 non-null  object
 2   fnlwgt          30162 non-null  int64 
 3   education       30162 non-null  object
 4   education.num   30162 non-null  int64 
 5   marital.status  30162 non-null  object
 6   occupation      30162 non-null  object
 7   relationship    30162 non-null  object
 8   race            30162 non-null  object
 9   sex             30162 non-null  object
 10  capital.gain    30162 non-null  int64 
 11  capital.loss    30162 non-null  int64 
 12  hours.per.week  30162 non-null  int64 
 13  native.country  30162 non-null  object
 14  income          30162 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [34]:
df.head()

age workclass  fnlwgt     education  education.num marital.status  \
1   82   Private  132870       HS-grad              9        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   
5   34   Private  216864       HS-grad              9       Divorced   
6   38   Private  150601          10th              6      Separated   

          occupation   relationship   race     sex  capital.gain  \
1    Exec-managerial  Not-in-family  White  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   
5      Other-service      Unmarried  White  Female             0   
6       Adm-clerical      Unmarried  White    Male             0   

   capital.loss  hours.per.week native.country income  
1          4356              18  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K  
5          3770              45  United-States  <=50K  
6          3770              40  United-States  <=50K

# Label Encoding

In [35]:
df_categorical = df.select_dtypes(include=['object'])

df_categorical.head()

workclass     education marital.status         occupation   relationship  \
1   Private       HS-grad        Widowed    Exec-managerial  Not-in-family   
3   Private       7th-8th       Divorced  Machine-op-inspct      Unmarried   
4   Private  Some-college      Separated     Prof-specialty      Own-child   
5   Private       HS-grad       Divorced      Other-service      Unmarried   
6   Private          10th      Separated       Adm-clerical      Unmarried   

    race     sex native.country income  
1  White  Female  United-States  <=50K  
3  White  Female  United-States  <=50K  
4  White  Female  United-States  <=50K  
5  White  Female  United-States  <=50K  
6  White    Male  United-States  <=50K

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_categorical = df_categorical.apply(le.fit_transform)
df_categorical.head()

workclass  education  marital.status  occupation  relationship  race  sex  \
1          2         11               6           3             1     4    0   
3          2          5               0           6             4     4    0   
4          2         15               5           9             3     4    0   
5          2         11               0           7             4     4    0   
6          2          0               5           0             4     4    1   

   native.country  income  
1              38       0  
3              38       0  
4              38       0  
5              38       0  
6              38       0

In [37]:
df = df.drop(df_categorical.columns, axis = 1)

df = pd.concat([df, df_categorical], axis = 1)

df.head()

age  fnlwgt  education.num  capital.gain  capital.loss  hours.per.week  \
1   82  132870              9             0          4356              18   
3   54  140359              4             0          3900              40   
4   41  264663             10             0          3900              40   
5   34  216864              9             0          3770              45   
6   38  150601              6             0          3770              40   

   workclass  education  marital.status  occupation  relationship  race  sex  \
1          2         11               6           3             1     4    0   
3          2          5               0           6             4     4    0   
4          2         15               5           9             3     4    0   
5          2         11               0           7             4     4    0   
6          2          0               5           0             4     4    1   

   native.country  income  
1              38       0  
3              38       0  
4              38       0  
5              38       0  
6              38       0

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 1 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30162 non-null  int64
 1   fnlwgt          30162 non-null  int64
 2   education.num   30162 non-null  int64
 3   capital.gain    30162 non-null  int64
 4   capital.loss    30162 non-null  int64
 5   hours.per.week  30162 non-null  int64
 6   workclass       30162 non-null  int32
 7   education       30162 non-null  int32
 8   marital.status  30162 non-null  int32
 9   occupation      30162 non-null  int32
 10  relationship    30162 non-null  int32
 11  race            30162 non-null  int32
 12  sex             30162 non-null  int32
 13  native.country  30162 non-null  int32
 14  income          30162 non-null  int32
dtypes: int32(9), int64(6)
memory usage: 2.6 MB


In [39]:
df['income'] = df['income'].astype('category')

df.head()

age  fnlwgt  education.num  capital.gain  capital.loss  hours.per.week  \
1   82  132870              9             0          4356              18   
3   54  140359              4             0          3900              40   
4   41  264663             10             0          3900              40   
5   34  216864              9             0          3770              45   
6   38  150601              6             0          3770              40   

   workclass  education  marital.status  occupation  relationship  race  sex  \
1          2         11               6           3             1     4    0   
3          2          5               0           6             4     4    0   
4          2         15               5           9             3     4    0   
5          2         11               0           7             4     4    0   
6          2          0               5           0             4     4    1   

   native.country income  
1              38      0  
3              38      0  
4              38      0  
5              38      0  
6              38      0

In [40]:
from sklearn.model_selection import train_test_split

x = df.drop('income', axis = 1)

y = df['income']

xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.3,
                                               random_state=45)

In [41]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(max_depth=5)

model.fit(xtrain, ytrain)

DecisionTreeClassifier(max_depth=5)

In [42]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

ypred = model.predict(xtest)

print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       0.86      0.95      0.91      6790
           1       0.79      0.55      0.65      2259

    accuracy                           0.85      9049
   macro avg       0.83      0.75      0.78      9049
weighted avg       0.85      0.85      0.84      9049



In [43]:
print(confusion_matrix(ytest, ypred))

[[6462  328]
 [1011 1248]]


In [44]:
print(accuracy_score(ytest, ypred))

0.8520278483810366


In [46]:
# 6462/(6462+328)

# Hyperparameter Tuning